Revert "Kernel: T2413: Update Linux Kernel to v4.19.119"
This reverts commit e2df78102dd77bf1338ec76031ab136e67ae7a28.

This actually breaks the WireGuard build:

wireguard/src/socket.c: In function ‘send6’:
wireguard/src/compat/compat.h:865:42: error: ‘const struct ipv6_stub’
has no member named ‘ipv6_dst_lookup’; did you mean ‘ipv6_dst_lookup_flow’?